spring:
  application:
    name: hello-app
  main.banner-mode: console

server:
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include: '*'

hello-app:
  #message: Spring Boot Rules! Actuator, Actuator, may you refresh your clients? I'll do it!
  message: Fine, after http://localhost:8080/actuator/refresh is called you'll see this
