spring:
  application:
    name: hello-app
  main.banner-mode: console

server:
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include: health, refresh

hello-app:
  message: Spring boot rules! And Actuator endpoint 'refresh' is refreshing this message
