spring:
  application:
    name: hello-app
  main.banner-mode: console

server:
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include: info, health, refresh

hello-app:
  message: Actuator endpoint 'refresh' is refreshing this message. Spring Boot Rules!
