spring:
  application:
    name: hello-app
  main.banner-mode: console

server:
  port: 8081
  
management:
  endpoints:
    web:
      exposure:
        include: health, refresh

hello-app:
  message: Spring boot rules!
